version: '3.8'

services:
  web:
    container_name: fintest
    build:
      dockerfile: api.Dockerfile
    restart: always
    volumes:
      - ./config.yml:/app/config.yml
    depends_on:
      - postgresql
    networks:
      - ps
    ports:
      - 8888:8888
    

  postgresql:
    container_name: fintest-psql
    build:
      dockerfile: db.Dockerfile
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - ps
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - 5432:5432


networks:
  ps:
